// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgoWGmSyUN700DPrvKcJ0fN8LaFFHxbAU',
    appId: '1:247211254473:web:7ad93db16be2aec92ae318',
    messagingSenderId: '247211254473',
    projectId: 'flutternoteapp-5698a',
    authDomain: 'flutternoteapp-5698a.firebaseapp.com',
    storageBucket: 'flutternoteapp-5698a.appspot.com',
    measurementId: 'G-EE9XZXW2SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTz1Qu6kB_z6o1Kh4u9SJLIQA3K_5633Y',
    appId: '1:247211254473:android:3e112d26023b91502ae318',
    messagingSenderId: '247211254473',
    projectId: 'flutternoteapp-5698a',
    storageBucket: 'flutternoteapp-5698a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6_MyOYlH6vVxdFLeI1tYFhXqSiWQ1Bp0',
    appId: '1:247211254473:ios:0f4e10d9d11918e82ae318',
    messagingSenderId: '247211254473',
    projectId: 'flutternoteapp-5698a',
    storageBucket: 'flutternoteapp-5698a.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6_MyOYlH6vVxdFLeI1tYFhXqSiWQ1Bp0',
    appId: '1:247211254473:ios:0f4e10d9d11918e82ae318',
    messagingSenderId: '247211254473',
    projectId: 'flutternoteapp-5698a',
    storageBucket: 'flutternoteapp-5698a.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgoWGmSyUN700DPrvKcJ0fN8LaFFHxbAU',
    appId: '1:247211254473:web:fb8c669e2fe6f5742ae318',
    messagingSenderId: '247211254473',
    projectId: 'flutternoteapp-5698a',
    authDomain: 'flutternoteapp-5698a.firebaseapp.com',
    storageBucket: 'flutternoteapp-5698a.appspot.com',
    measurementId: 'G-FG3MQ8RN52',
  );
}
